#!/usr/bin/env bash
# Generated by quickpat compose -- do not edit
# Creates Kubernetes secrets for secure-agent-workspace.
# Run before helm install if not using values.yaml secrets.

set -euo pipefail
NAMESPACE="${NAMESPACE:-secure-agent-workspace}"

echo "Creating secrets for namespace: $NAMESPACE"

echo "Secrets created successfully."
echo "You can now run: helm install secure-agent-workspace ./chart -n $NAMESPACE"
